### ISSUE TITLE
请问大佬这个项目是不是失效了？

### ISSUE THREAD

**Issue by TommyLee9527** [5ime/bilidown#1]
我把获取的video_url放到播放器 显示无法连接，请问是不是失效了？？？

**Comment by 5ime** [comment]
没有，哔哩哔哩需要设置referer

**Comment by TommyLee9527** [comment]
请问有没有教程啊？

**Comment by 5ime** [comment]
https://github.com/5ime/bilidown/blob/4688da0a8f1d8586528aaba03c7c6af7855cb002/bilidown.py#L22

**Comment by TommyLee9527** [comment]
然后我在chrome控制台找哪个请求里面的Referer的值啊？？

**Comment by 5ime** [comment]
没看明白
哔哩哔哩播放或者下载视频header请求头Referer里需要包含: https://www.bilibili.com

**Comment by TommyLee9527** [comment]
你的意思是我要把Referer的值放进video_url 然后播放吗？

**Comment by 5ime** [comment]
不是
Referer：https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Referer

**Comment by TommyLee9527** [comment]
potplayer还真有referer命令行，搞定了，可以正常播放。

**Comment by TommyLee9527** [comment]
非常感谢你的指导，非常感谢！
