### ISSUE TITLE
关于清晰度问题

### ISSUE THREAD

**Issue by TommyLee9527** [5ime/bilidown#3]
请问对获取的 video_url 进行在线播放的时候清晰的最高只有720p是什么原因啊？

**Comment by 5ime** [comment]
方便发一下哔哩哔哩视频链接吗？

**Comment by TommyLee9527** [comment]
BV1P5411V7QZ
这个BV号，明明浏览器播放有1080p清晰度，转到播放器里默认就是720p，不知道原因是什么，麻烦你帮忙分析一下。

**Comment by 5ime** [comment]
emm... 我这确确实实是1080p
![image](https://user-images.githubusercontent.com/31686695/146771598-d9a80860-611c-43d3-bc02-1defcc235dc8.png)

**Comment by TommyLee9527** [comment]
找到原因了
video_info = json.loads(s.get('https://api.bilibili.com/x/player/playurl?bvid='+video_id+'&cid='+str(video)+'&qn=80&otype=json',headers=header,cookies=cookie).text)
我把cookies=cookie删掉了，结果变720P了。
我看网上说s=requests.session()实例化之后可以保持登录状态，所以我以为这里就再不需要cookies了呢，能解释一下我错在哪里了吗
